# Change these first
owner: fairvisor # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Fairvisor main site
    url: https://www.fairvisor.com
  - name: Fairvisor documentation
    url: https://docs.fairvisor.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.fairvisor.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/fairvisor/status/master/static/logo.svg
  favicon: https://raw.githubusercontent.com/fairvisor/status/master/static/logo.svg
  name: Fairvisor Status
  introTitle: "Fairvisor Status"
  introMessage: "Current status of Fairvisor services. We monitor uptime and performance in real time."
  theme: dark
  links:
    - rel: stylesheet
      href: https://raw.githubusercontent.com/fairvisor/status/master/static/fairvisor-theme.css
  navbar:
    - title: Status
      href: /
    - title: fairvisor.com
      href: https://www.fairvisor.com
    - title: Docs
      href: https://docs.fairvisor.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
